version: 2.1
orbs:
  python: circleci/python@0.3.7
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python my_script.py
workflows:
  build_and_test:
    jobs:
      - build
